# Generated by Django 5.0.1 on 2026-01-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('current_version', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('chat', 'chat'), ('ai search', 'ai search'), ('image generation', 'image generation'), ('vedio generation', 'vedio generation'), ('coding assistant', 'coding assistant'), ('document', 'document'), ('multi model', 'multi model'), ('other', 'other')], default='chat', max_length=200)),
            ],
        ),
    ]
